[build]
  command = "CI=false npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  VITE_API_URL = "https://babismell-backend.fly.dev"
  VITE_SOCKET_URL = "wss://babismell-backend.fly.dev"
  VITE_FIREBASE_API_KEY = "AIzaSyDZVlpVXqYxZQvgXXZBVzJaQVHxXVGAzKw"
  VITE_FIREBASE_AUTH_DOMAIN = "babismell-2024.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "babismell-2024"
  VITE_FIREBASE_STORAGE_BUCKET = "babismell-2024.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "1234567890"
  VITE_FIREBASE_APP_ID = "1:1234567890:web:abcdef1234567890"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  autoLaunch = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Authorization"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"