[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npx prisma generate && npm run build"
watchPatterns = ["server/**/*"]

[deploy]
startCommand = "cd server && NODE_ENV=production node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 3000
