[build]
directory = "backend"
builder = "nixpacks"
buildCommand = "cd /app/backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd /app/backend && NODE_ENV=production node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
internal_port = 3000
